version: "3.8"
services:
  postgres:
    container_name: database
    image: postgres:17
    hostname: ${DATABASE_HOST}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./src/utils/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  postgres-test:
    container_name: database_test
    image: postgres:17
    hostname: test-database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_todos
    volumes:
      - ./database_test:/var/lib/postgresql/data
      - ./src/utils/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    restart: always
