name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Frontend Dependencies
        run: cd client && npm install
      - name: Run Frontend Tests
        run: cd client && npm run test

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Backend Dependencies
        run: cd client && npm install
      - name: Run Backend Tests
        run: |
          cd server
          node -e "console.log('Backend test placeholder: All systems go!')"

  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: |
          cd e2e-tests && npm install
          cd server && npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start Backend
        run: |
          cd server
          npm install
          npm run test
      - name: Start Frontend
        run: |
          cd client
          npm install
          npm run build
          npx serve -s client/dist &
          npx wait-on http://localhost:3000
      - name: Run e2e tests
        run: cd e2e-tests && npm run test:cicd --reporter=html
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 30
