name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Frontend Dependencies
        run: cd client && npm install
      - name: Run Frontend Tests
        run: cd client && npm run test

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Backend Dependencies
        run: cd client && npm install
      - name: Run Backend Tests
        run: |
          cd server
          node -e "console.log('Backend test placeholder: All systems go!')"

  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: test
          POSTGRES_DB: todos
    env:
      DATABASE_URL: postgres://tester:test@localhost:5432/todos
      CICD_URL: http://localhost:3000
      PORT: 3000
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # - uses: actions/setup-node@v4
        # with:
        #   node-version: lts/*
      - name: Install e2e-test Dependencies
        run: cd e2e-tests && npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build the App
        run: |
          cd client
          bun install
          cd ../server
          bun install
          bun run build


        # run: |
        #   cd client
        #   npm install
        #   npm run build
      - name: Start App
        run: |
          cd server
          bun run test &
          sleep 5
      #   run: |
      # - name: Start App
      #   run: |
      #     npx serve -s client/dist &
      #     npx wait-on http://localhost:3000
      - name: Run e2e tests
        run: cd e2e-tests && npm run test:cicd --reporter=html
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 30
